### ISSUE TITLE
Restricted Objects in Paginated GridField shows 'No items found'

### ISSUE THREAD

**Issue by talbet** [nyeholt/silverstripe-restrictedobjects#17]
If I have a hasMany relationship on pages (a 'Related Pages' field), and this is displayed in a GridField, the `canView()` check is executed after the pagination is calculated. 

In a large page tree where a user may only have access to a few pages, this results in a gridfield that is mostly empty, displaying 'No items found' with grid rows appearing sparsely across ajax requests. Ideally the `canView()` would filter the pages available to the user, before pagination takes place. 

This is more a shortcoming with the Silverstripe CMS, and its default permissions model, but I was hoping your module might be able to help overcome this problem?

**Comment by nyeholt** [comment]
It'd need an adjustment of how the pagination is determined - either a custom GridFieldPaginator, or forcing the list the grid is wrapped around to be the already-filtered list. Though doing the second may not work properly if creating new items etc.

**Comment by talbet** [comment]
Going with the second option, thanks for the advice. It means pre-filtering list in a seperate area of the code that isn't security specific (ModelAdmin mainly), but seems like the best trade off as the area of the site I need to lock down is quite small.
